### ISSUE TITLE
bug in humidity readout?

### ISSUE THREAD

**Issue by kaido42** [utkumaden/esp-idf-bmx280#3]
```
*humidity = bme280_compensate_H_int32(bmx280, 
      (buffer[0] << 8) | buffer[0]
);

```

looks like a typo to me, bits from buffer[0] are 'double-used' and bits from buffer[1] are ignored ..

looks better like this:

```
*humidity = bme280_compensate_H_int32(bmx280, 
      (buffer[0] << 8) | buffer[1]
);

```

**Comment by utkumaden** [comment]
This is very likely a typo. When I wrote this drivers I didn't have the BME280 IC to test the driver with. If you have the hardware would you be kind to write a pull request for this? If not I can fix this for you.

**Comment by utkumaden** [comment]
This has been fixed in the latest patch. Thank you for reporting.
