### ISSUE TITLE
Unable to Parse Symbol 'BMX280_STANDBY_20M'

### ISSUE THREAD

**Issue by abattle** [utkumaden/esp-idf-bmx280#5]
When following the provided usage instructions, I encountered an issue where the symbol 'BMX280_STANDBY_20M' could not be parsed.
ESP-IDF version：v5.3.1

**Comment by utkumaden** [comment]
Hello, sorry for responding to this later than usual. The enum member you are looking for is `BME280_STANDBY_20M`. Notice, not `BMX`. This is because that mode is specific to BME280, and is not available on the older BMP280 devices.

Can you please confirm in your code?

**Comment by utkumaden** [comment]
This has been resolved the the latest version. Thank your for taking the time to report this.
